#!/bin/sh
unset NODE_OPTIONS
ELECTRON_RUN_AS_NODE=1 "/opt/cursor/usr/share/cursor/cursor" "/home/pappanos/.config/Cursor/User/globalStorage/github.copilot-chat/debugCommand/copilotDebugCommand.js" "cursor://github.copilot-chat" "" "$@"