[bar/popup_general]
monitor = ${env:MONITOR:}
inherit = bar/popup_base
width = 300
offset-x = 1%
; offset-y = 90.8%
modules-left = sep quick-edit
modules-center = backlight-toggle sep idle-toggle sep wal sep sep 
modules-right = keyboard sep
