[bar/popup_sysinfo]
monitor = ${env:MONITOR:}
inherit = bar/popup_base
width = 850
offset-x = 10%
; offset-y = 90.8%
modules-left = sep cpu-usage sep cpu-temp
modules-center = storage sep ram sep backlight
modules-right = gpu-temp sep gpu-usage sep
