[bar/popup_bluetooth]
monitor = ${env:MONITOR:}
inherit = bar/popup_base  
width = 400
offset-x = 70%
; offset-y = 90.8%

; You'll need to create these modules or use existing ones
modules-left = sep bluetooth-icon bluetooth
modules-center = 
modules-right = mic-volume mic-icon sep
