;; ┌────────────────────────────────────────────────────────────┐
;; │░█▀█░█▀█░█░░░█░█░█▀▄░█▀█░█▀▄░░░░░░░░░█▀▀░█▀█░█░░░█▀█░█▀▄░█▀▀│
;; │░█▀▀░█░█░█░░░░█░░█▀▄░█▀█░█▀▄░░░░▀░░░░█░░░█░█░█░░░█░█░█▀▄░▀▀█│
;; │░▀░░░▀▀▀░▀▀▀░░▀░░▀▀░░▀░▀░▀░▀░░░░▀░░░░▀▀▀░▀▀▀░▀▀▀░▀▀▀░▀░▀░▀▀▀│
;; │░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░│
;; └────────────────────────────────────────────────────────────┘
;; *-*-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[color]
;; Use pywal.sh in scripts directory to use colors from an image/wallpaper.

;; main colors
background = #160916
background-alt = #6c596c
foreground = #ffffff
foreground-alt = #6c596c
primary = #d58952
white = #ffffff
black = #000000

;; normal colors
red = #d58952
pink = #c9a985
purple = #c9a985
blue = #833d3a
cyan = #829e9e
teal = #829e9e
green = #5291a7
lime = #5291a7
yellow = #f0cc87
amber = #f0cc87
orange = #d58952
brown = #c9a985
gray = #829e9e
indigo = #c9a985
blue-gray = #833d3a
